
server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://sideproject.cgxivbds0jyg.ap-northeast-2.rds.amazonaws.com:3306/sideproject
    username: admin
    password: qwer1234
  thymeleaf:
    cache: false


#logging:
#  level:
#    root: debug

